kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-boilerplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-boilerplate
  template:
    metadata:
      labels:
        app: react-boilerplate
    spec:
      containers:
        - name: react-boilerplate
          image: reactboilerplate
          imagePullPolicy: Never
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: react-boilerplate
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: react-boilerplate